In [13]:
import numpy as np

In [14]:
from ucimlrepo import fetch_ucirepo

# Load the official UCI PhiUSIIL phishing URL dataset
phiusiil = fetch_ucirepo(id=967)

# Separate features and target
X = phiusiil.data.features
y = phiusiil.data.targets

print("Dataset loaded successfully!")
print("Features shape:", X.shape)
print("Target shape:", y.shape)

Dataset loaded successfully!
Features shape: (235795, 54)
Target shape: (235795, 1)

In [15]:
# Inspect the dataset
print("Feature columns:")
print(X.columns.tolist())

print("\nFirst 5 rows:")
display(X.head())

print("\nTarget values:")
print(y.head())

print("\nTarget distribution:")
print(y.value_counts())

Feature columns:
['URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP', 'TLD', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength', 'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef']

First 5 rows:

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,1,0,0,1,34,20,28,119,0,124
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,0,1,50,9,8,39,0,217
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,0,1,10,2,7,42,2,5
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,0,1,1,1,3,27,15,22,1,31
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,1,0,1,244,15,34,72,1,85

Target values:
   label
0      1
1      1
2      1
3      1
4      1

Target distribution:
label
1        134850
0        100945
Name: count, dtype: int64

In [16]:
print("Data types:")
print(X.dtypes)

print("\nMissing values:")
print(X.isnull().sum())

print("\nDuplicate rows:")
print(X.duplicated().sum())

Data types:
URL                               str
URLLength                       int64
Domain                            str
DomainLength                    int64
IsDomainIP                      int64
TLD                               str
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
Title                             str
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
dtype: object

Missing values:
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
dtype: int64

Duplicate rows:
0

In [17]:
# Separate text and numerical features

text_columns = X.select_dtypes(include=["object"]).columns.tolist()
numeric_columns = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Text columns:")
for column in text_columns:
    print("•", column)

print("\nNumber of text columns:", len(text_columns))

print("\nNumber of numerical columns:", len(numeric_columns))

print("\nNumerical columns:")
for column in numeric_columns:
    print("•", column)

Text columns:
• URL
• Domain
• TLD
• Title

Number of text columns: 4

Number of numerical columns: 50

Numerical columns:
• URLLength
• DomainLength
• IsDomainIP
• URLSimilarityIndex
• CharContinuationRate
• TLDLegitimateProb
• URLCharProb
• TLDLength
• NoOfSubDomain
• HasObfuscation
• NoOfObfuscatedChar
• ObfuscationRatio
• NoOfLettersInURL
• LetterRatioInURL
• NoOfDegitsInURL
• DegitRatioInURL
• NoOfEqualsInURL
• NoOfQMarkInURL
• NoOfAmpersandInURL
• NoOfOtherSpecialCharsInURL
• SpacialCharRatioInURL
• IsHTTPS
• LineOfCode
• LargestLineLength
• HasTitle
• DomainTitleMatchScore
• URLTitleMatchScore
• HasFavicon
• Robots
• IsResponsive
• NoOfURLRedirect
• NoOfSelfRedirect
• HasDescription
• NoOfPopup
• NoOfiFrame
• HasExternalFormSubmit
• HasSocialNet
• HasSubmitButton
• HasHiddenFields
• HasPasswordField
• Bank
• Pay
• Crypto
• HasCopyrightInfo
• NoOfImage
• NoOfCSS
• NoOfJS
• NoOfSelfRef
• NoOfEmptyRef
• NoOfExternalRef

C:\Users\ASUS\AppData\Local\Temp\ipykernel_38220\389466255.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = X.select_dtypes(include=["object"]).columns.tolist()

In [18]:
# Check numerical features for missing and infinite values

print("Missing numerical values:")
print(X[numeric_columns].isnull().sum().sum())

print("\nInfinite numerical values:")
print(np.isinf(X[numeric_columns].to_numpy()).sum())

print("\nBasic statistics:")
display(X[numeric_columns].describe().T)

Missing numerical values:
0

Infinite numerical values:
0

Basic statistics:

,count,mean,std,min,25%,50%,75%,max
URLLength,235795.0,34.573095,41.314153,13.000000,23.000000,27.000000,34.000000,6.097000e+03
DomainLength,235795.0,21.470396,9.150793,4.000000,16.000000,20.000000,24.000000,1.100000e+02
IsDomainIP,235795.0,0.002706,0.051946,0.000000,0.000000,0.000000,0.000000,1.000000e+00
URLSimilarityIndex,235795.0,78.430778,28.976055,0.155574,57.024793,100.000000,100.000000,1.000000e+02
CharContinuationRate,235795.0,0.845508,0.216632,0.000000,0.680000,1.000000,1.000000,1.000000e+00
TLDLegitimateProb,235795.0,0.260423,0.251628,0.000000,0.005977,0.079963,0.522907,5.229071e-01
URLCharProb,235795.0,0.055747,0.010587,0.001083,0.050747,0.057970,0.062875,9.082366e-02
TLDLength,235795.0,2.764456,0.599739,2.000000,2.000000,3.000000,3.000000,1.300000e+01
NoOfSubDomain,235795.0,1.164758,0.600969,0.000000,1.000000,1.000000,1.000000,1.000000e+01
HasObfuscation,235795.0,0.002057,0.045306,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfObfuscatedChar,235795.0,0.024861,1.876249,0.000000,0.000000,0.000000,0.000000,4.470000e+02
ObfuscationRatio,235795.0,0.000138,0.003817,0.000000,0.000000,0.000000,0.000000,3.480000e-01
NoOfLettersInURL,235795.0,19.428919,29.090330,0.000000,10.000000,14.000000,20.000000,5.191000e+03
LetterRatioInURL,235795.0,0.515946,0.123315,0.000000,0.435000,0.519000,0.594000,9.260000e-01
NoOfDegitsInURL,235795.0,1.881011,11.886695,0.000000,0.000000,0.000000,0.000000,2.011000e+03
DegitRatioInURL,235795.0,0.028616,0.070897,0.000000,0.000000,0.000000,0.000000,6.840000e-01
NoOfEqualsInURL,235795.0,0.062241,0.934704,0.000000,0.000000,0.000000,0.000000,1.760000e+02
NoOfQMarkInURL,235795.0,0.029403,0.193505,0.000000,0.000000,0.000000,0.000000,4.000000e+00
NoOfAmpersandInURL,235795.0,0.025056,0.836448,0.000000,0.000000,0.000000,0.000000,1.490000e+02
NoOfOtherSpecialCharsInURL,235795.0,2.340198,3.527603,0.000000,1.000000,1.000000,3.000000,4.990000e+02
SpacialCharRatioInURL,235795.0,0.063309,0.032393,0.000000,0.038000,0.050000,0.083000,3.970000e-01
IsHTTPS,235795.0,0.782625,0.412461,0.000000,1.000000,1.000000,1.000000,1.000000e+00
LineOfCode,235795.0,1141.900443,3419.950513,2.000000,18.000000,429.000000,1277.000000,4.426660e+05
LargestLineLength,235795.0,12789.532624,152201.099228,22.000000,200.000000,1090.000000,8047.000000,1.397573e+07
HasTitle,235795.0,0.861261,0.345675,0.000000,1.000000,1.000000,1.000000,1.000000e+00
DomainTitleMatchScore,235795.0,50.131427,49.676981,0.000000,0.000000,75.000000,100.000000,1.000000e+02
URLTitleMatchScore,235795.0,52.122098,49.600564,0.000000,0.000000,100.000000,100.000000,1.000000e+02
HasFavicon,235795.0,0.361768,0.480513,0.000000,0.000000,0.000000,1.000000,1.000000e+00
Robots,235795.0,0.266541,0.442151,0.000000,0.000000,0.000000,1.000000,1.000000e+00
IsResponsive,235795.0,0.624513,0.484249,0.000000,0.000000,1.000000,1.000000,1.000000e+00
NoOfURLRedirect,235795.0,0.133438,0.340048,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfSelfRedirect,235795.0,0.040107,0.196210,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasDescription,235795.0,0.440183,0.496410,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfPopup,235795.0,0.221765,3.870540,0.000000,0.000000,0.000000,0.000000,6.020000e+02
NoOfiFrame,235795.0,1.588638,5.762561,0.000000,0.000000,0.000000,1.000000,1.602000e+03
HasExternalFormSubmit,235795.0,0.043987,0.205067,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasSocialNet,235795.0,0.456570,0.498111,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasSubmitButton,235795.0,0.414301,0.492602,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasHiddenFields,235795.0,0.377799,0.484838,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasPasswordField,235795.0,0.102263,0.302994,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Bank,235795.0,0.127089,0.333074,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Pay,235795.0,0.237007,0.425247,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Crypto,235795.0,0.023474,0.151403,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasCopyrightInfo,235795.0,0.486775,0.499826,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfImage,235795.0,26.075689,79.411815,0.000000,0.000000,8.000000,29.000000,8.956000e+03
NoOfCSS,235795.0,6.333111,74.866296,0.000000,0.000000,2.000000,8.000000,3.582000e+04
NoOfJS,235795.0,10.522305,22.312192,0.000000,0.000000,6.000000,15.000000,6.957000e+03
NoOfSelfRef,235795.0,65.071113,176.687539,0.000000,0.000000,12.000000,88.000000,2.739700e+04
NoOfEmptyRef,235795.0,2.377629,17.641097,0.000000,0.000000,0.000000,1.000000,4.887000e+03
NoOfExternalRef,235795.0,49.262516,161.027430,0.000000,1.000000,10.000000,57.000000,2.751600e+04

In [19]:
from sklearn.model_selection import train_test_split

# Use the 50 numerical features for the first phishing model
X_numeric = X[numeric_columns].copy()

# Convert target to a 1-dimensional array
y_phishing = y["label"]

# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X_numeric,
    y_phishing,
    test_size=0.20,
    random_state=42,
    stratify=y_phishing
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

Training samples: 188636
Testing samples: 47159

Training class distribution:
label
1    107880
0     80756
Name: count, dtype: int64

Testing class distribution:
label
1    26970
0    20189
Name: count, dtype: int64

In [20]:
from sklearn.ensemble import RandomForestClassifier

# Create the phishing detection model
phishing_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

# Train the model
phishing_model.fit(X_train, y_train)

print("Phishing model trained successfully!")

Phishing model trained successfully!

In [21]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

# Make predictions
y_pred = phishing_model.predict(X_test)

# Get probabilities for the phishing class (label 0)
y_proba_phishing = phishing_model.predict_proba(X_test)[:, 0]

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        labels=[0, 1],
        target_names=["Phishing", "Legitimate"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred, labels=[0, 1]))

print("\nROC-AUC:")
print(round(roc_auc_score(y_test, y_proba_phishing), 4))

Accuracy: 100.0 %

Classification Report:
              precision    recall  f1-score   support

    Phishing       1.00      1.00      1.00     20189
  Legitimate       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

Confusion Matrix:
[[20189     0]
 [    0 26970]]

ROC-AUC:
0.0

In [25]:
# Calculate ROC-AUC with phishing treated as the positive class

y_test_phishing = (y_test == 0).astype(int)

roc_auc = roc_auc_score(
    y_test_phishing,
    y_proba_phishing
)

print("Correct ROC-AUC:", round(roc_auc, 4))

Correct ROC-AUC: 1.0

In [26]:
# Examine the most important features
import pandas as pd
feature_importance = pd.DataFrame({
    "feature": numeric_columns,
    "importance": phishing_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="importance",
    ascending=False
)

display(feature_importance.head(15))

                       feature  importance
3           URLSimilarityIndex    0.193731
49             NoOfExternalRef    0.167314
22                  LineOfCode    0.136339
44                   NoOfImage    0.110585
47                 NoOfSelfRef    0.092020
46                      NoOfJS    0.071100
36                HasSocialNet    0.043285
32              HasDescription    0.023982
43            HasCopyrightInfo    0.023858
45                     NoOfCSS    0.022692
19  NoOfOtherSpecialCharsInURL    0.014740
21                     IsHTTPS    0.012957
23           LargestLineLength    0.012161
14             NoOfDegitsInURL    0.008896
37             HasSubmitButton    0.007133

In [27]:
# Check how strongly each feature differs between phishing and legitimate URLs

feature_check = X_numeric.copy()
feature_check["label"] = y_phishing

comparison = feature_check.groupby("label").mean().T

comparison.columns = ["Phishing (0)", "Legitimate (1)"]

display(comparison)

                            Phishing (0)  Legitimate (1)
URLLength                      45.720293       26.228610
DomainLength                   24.465144       19.228610
IsDomainIP                      0.006320        0.000000
URLSimilarityIndex             49.616973      100.000000
CharContinuationRate            0.728395        0.933176
TLDLegitimateProb               0.232099        0.281625
URLCharProb                     0.049999        0.060050
TLDLength                       2.819327        2.723382
NoOfSubDomain                   1.168894        1.161661
HasObfuscation                  0.004805        0.000000
NoOfObfuscatedChar              0.058071        0.000000
ObfuscationRatio                0.000323        0.000000
NoOfLettersInURL               28.106583       12.933059
LetterRatioInURL                0.568366        0.476705
NoOfDegitsInURL                 4.326217        0.050597
DegitRatioInURL                 0.064018        0.002115
NoOfEqualsInURL                 0.145386        0.000000
NoOfQMarkInURL                  0.068681        0.000000
NoOfAmpersandInURL              0.058527        0.000000
NoOfOtherSpecialCharsInURL      3.803467        1.244835
SpacialCharRatioInURL           0.083285        0.048356
IsHTTPS                         0.492238        1.000000
LineOfCode                     65.730467     1947.491680
LargestLineLength           20021.448244     7375.919555
HasTitle                        0.677587        0.998754
DomainTitleMatchScore          16.548205       75.270904
URLTitleMatchScore             21.198164       75.270904
HasFavicon                      0.087572        0.567023
Robots                          0.065897        0.416737
IsResponsive                    0.317460        0.854364
NoOfURLRedirect                 0.151696        0.119770
NoOfSelfRedirect                0.057447        0.027126
HasDescription                  0.044163        0.736633
NoOfPopup                       0.009758        0.380467
NoOfiFrame                      0.084581        2.714535
HasExternalFormSubmit           0.004270        0.073719
HasSocialNet                    0.005062        0.794557
HasSubmitButton                 0.084898        0.660882
HasHiddenFields                 0.093279        0.590782
HasPasswordField                0.053871        0.138487
Bank                            0.054346        0.181542
Pay                             0.060191        0.369366
Crypto                          0.006043        0.036522
HasCopyrightInfo                0.057338        0.808239
NoOfImage                       0.866492       44.946600
NoOfCSS                         0.439616       10.744820
NoOfJS                          0.890336       17.732532
NoOfSelfRef                     0.496032      113.410241
NoOfEmptyRef                    0.150379        4.044887
NoOfExternalRef                 1.128119       85.294601

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Test how powerful URLSimilarityIndex is by itself
X_similarity = X[["URLSimilarityIndex"]]

X_sim_train, X_sim_test, y_sim_train, y_sim_test = train_test_split(
    X_similarity,
    y_phishing,
    test_size=0.20,
    random_state=42,
    stratify=y_phishing
)

similarity_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

similarity_model.fit(X_sim_train, y_sim_train)

y_sim_pred = similarity_model.predict(X_sim_test)

print("Accuracy using ONLY URLSimilarityIndex:")
print(round(accuracy_score(y_sim_test, y_sim_pred) * 100, 2), "%")

print("\nClassification Report:")
print(
    classification_report(
        y_sim_test,
        y_sim_pred,
        labels=[0, 1],
        target_names=["Phishing", "Legitimate"]
    )
)

Accuracy using ONLY URLSimilarityIndex:
99.63 %

Classification Report:
              precision    recall  f1-score   support

    Phishing       1.00      0.99      1.00     20189
  Legitimate       0.99      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [29]:
# Remove the extremely dominant URLSimilarityIndex feature
numeric_columns_reduced = [
    column for column in numeric_columns
    if column != "URLSimilarityIndex"
]

X_reduced = X[numeric_columns_reduced].copy()

X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(
    X_reduced,
    y_phishing,
    test_size=0.20,
    random_state=42,
    stratify=y_phishing
)

reduced_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

reduced_model.fit(X_train_reduced, y_train_reduced)

y_reduced_pred = reduced_model.predict(X_test_reduced)

print("Features used:", len(numeric_columns_reduced))
print("Accuracy without URLSimilarityIndex:",
      round(accuracy_score(y_test_reduced, y_reduced_pred) * 100, 2), "%")

print("\nClassification Report:")
print(
    classification_report(
        y_test_reduced,
        y_reduced_pred,
        labels=[0, 1],
        target_names=["Phishing", "Legitimate"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_reduced,
    y_reduced_pred,
    labels=[0, 1]
))

Features used: 49
Accuracy without URLSimilarityIndex: 99.99 %

Classification Report:
              precision    recall  f1-score   support

    Phishing       1.00      1.00      1.00     20189
  Legitimate       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159


Confusion Matrix:
[[20184     5]
 [    1 26969]]

In [30]:
# Features that can be derived from the URL itself
# These will be usable by our Streamlit application.

url_only_features = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "URLSimilarityIndex",
    "CharContinuationRate",
    "TLDLegitimateProb",
    "URLCharProb",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",
    "IsHTTPS"
]

print("URL-only features:", len(url_only_features))

print("\nFeatures:")
for feature in url_only_features:
    print("•", feature)

URL-only features: 22

Features:
• URLLength
• DomainLength
• IsDomainIP
• URLSimilarityIndex
• CharContinuationRate
• TLDLegitimateProb
• URLCharProb
• TLDLength
• NoOfSubDomain
• HasObfuscation
• NoOfObfuscatedChar
• ObfuscationRatio
• NoOfLettersInURL
• LetterRatioInURL
• NoOfDegitsInURL
• DegitRatioInURL
• NoOfEqualsInURL
• NoOfQMarkInURL
• NoOfAmpersandInURL
• NoOfOtherSpecialCharsInURL
• SpacialCharRatioInURL
• IsHTTPS

In [31]:
# Features that can be reproduced directly from a raw URL

reproducible_features = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",
    "IsHTTPS"
]

X_url = X[reproducible_features].copy()

print("URL-only features:", len(reproducible_features))
print("Training data shape:", X_url.shape)

print("\nFeatures:")
for feature in reproducible_features:
    print("•", feature)

URL-only features: 18
Training data shape: (235795, 18)

Features:
• URLLength
• DomainLength
• IsDomainIP
• TLDLength
• NoOfSubDomain
• HasObfuscation
• NoOfObfuscatedChar
• ObfuscationRatio
• NoOfLettersInURL
• LetterRatioInURL
• NoOfDegitsInURL
• DegitRatioInURL
• NoOfEqualsInURL
• NoOfQMarkInURL
• NoOfAmpersandInURL
• NoOfOtherSpecialCharsInURL
• SpacialCharRatioInURL
• IsHTTPS

In [32]:
# Split URL-only features into training and testing sets

X_url_train, X_url_test, y_url_train, y_url_test = train_test_split(
    X_url,
    y_phishing,
    test_size=0.20,
    random_state=42,
    stratify=y_phishing
)

print("URL training samples:", X_url_train.shape[0])
print("URL testing samples:", X_url_test.shape[0])

print("\nTraining class distribution:")
print(y_url_train.value_counts())

print("\nTesting class distribution:")
print(y_url_test.value_counts())

URL training samples: 188636
URL testing samples: 47159

Training class distribution:
label
1    107880
0     80756
Name: count, dtype: int64

Testing class distribution:
label
1    26970
0    20189
Name: count, dtype: int64

In [33]:
from sklearn.ensemble import RandomForestClassifier

# Train the URL-only phishing detector
url_phishing_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

url_phishing_model.fit(X_url_train, y_url_train)

print("URL-only phishing model trained successfully!")

URL-only phishing model trained successfully!

In [34]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

# Predictions
y_url_pred = url_phishing_model.predict(X_url_test)

# Probability of phishing (class 0)
y_url_proba_phishing = url_phishing_model.predict_proba(X_url_test)[:, 0]

# Convert labels so phishing = 1 for ROC-AUC
y_url_test_phishing = (y_url_test == 0).astype(int)

# Metrics
accuracy = accuracy_score(y_url_test, y_url_pred)

roc_auc = roc_auc_score(
    y_url_test_phishing,
    y_url_proba_phishing
)

print("Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(
    classification_report(
        y_url_test,
        y_url_pred,
        labels=[0, 1],
        target_names=["Phishing", "Legitimate"]
    )
)

print("Confusion Matrix:")
print(
    confusion_matrix(
        y_url_test,
        y_url_pred,
        labels=[0, 1]
    )
)

print("\nROC-AUC:", round(roc_auc, 4))

Accuracy: 99.73 %

Classification Report:
              precision    recall  f1-score   support

    Phishing       1.00      0.99      1.00     20189
  Legitimate       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

Confusion Matrix:
[[20080   109]
 [   20 26950]]

ROC-AUC: 0.9984

In [35]:
from sklearn.model_selection import train_test_split

# Split the training data into:
# 80% actual training
# 20% validation

X_url_train_final, X_url_val, y_url_train_final, y_url_val = train_test_split(
    X_url_train,
    y_url_train,
    test_size=0.20,
    random_state=42,
    stratify=y_url_train
)

print("Final training samples:", X_url_train_final.shape[0])
print("Validation samples:", X_url_val.shape[0])

print("\nValidation class distribution:")
print(y_url_val.value_counts())

Final training samples: 150908
Validation samples: 37728

Validation class distribution:
label
1    21576
0    16152
Name: count, dtype: int64

In [36]:
# Train a fresh model using only the final training set

url_validation_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

url_validation_model.fit(
    X_url_train_final,
    y_url_train_final
)

print("Validation model trained successfully!")

Validation model trained successfully!

In [37]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Get phishing probabilities from the validation model
# Class 0 = Phishing
y_val_proba_phishing = url_validation_model.predict_proba(X_url_val)[:, 0]

# Convert actual labels so:
# 1 = Phishing
# 0 = Legitimate
y_val_phishing = (y_url_val == 0).astype(int)

# Test different probability thresholds
thresholds = [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70]

print("Threshold | Precision | Recall | F1")
print("-" * 42)

for threshold in thresholds:
    y_val_pred_phishing = (
        y_val_proba_phishing >= threshold
    ).astype(int)

    precision = precision_score(
        y_val_phishing,
        y_val_pred_phishing
    )

    recall = recall_score(
        y_val_phishing,
        y_val_pred_phishing
    )

    f1 = f1_score(
        y_val_phishing,
        y_val_pred_phishing
    )

    print(
        f"{threshold:9.2f} | "
        f"{precision:9.3f} | "
        f"{recall:6.3f} | "
        f"{f1:5.3f}"
    )

Threshold | Precision | Recall | F1
------------------------------------------
     0.30 |     0.998 |  0.995 | 0.997
     0.35 |     0.999 |  0.995 | 0.997
     0.40 |     0.999 |  0.995 | 0.997
     0.45 |     0.999 |  0.994 | 0.997
     0.50 |     0.999 |  0.994 | 0.997
     0.55 |     0.999 |  0.994 | 0.997
     0.60 |     0.999 |  0.994 | 0.997
     0.65 |     1.000 |  0.993 | 0.996
     0.70 |     1.000 |  0.993 | 0.996

In [38]:
# Lock the phishing probability threshold
URL_PHISHING_THRESHOLD = 0.40

print("Locked phishing threshold:", URL_PHISHING_THRESHOLD)

Locked phishing threshold: 0.4

In [39]:
# Train the final URL-only phishing model
# using the complete training set

final_url_phishing_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

final_url_phishing_model.fit(
    X_url_train,
    y_url_train
)

print("Final URL-only phishing model trained successfully!")

Final URL-only phishing model trained successfully!

In [40]:
# Final evaluation using the locked 0.40 threshold

# Get phishing probabilities
y_test_proba_phishing = (
    final_url_phishing_model.predict_proba(X_url_test)[:, 0]
)

# Convert labels:
# 0 = Legitimate
# 1 = Phishing
y_test_phishing = (y_url_test == 0).astype(int)

# Apply the locked threshold
y_test_pred_phishing = (
    y_test_proba_phishing >= URL_PHISHING_THRESHOLD
).astype(int)

# Calculate metrics
final_precision = precision_score(
    y_test_phishing,
    y_test_pred_phishing
)

final_recall = recall_score(
    y_test_phishing,
    y_test_pred_phishing
)

final_f1 = f1_score(
    y_test_phishing,
    y_test_pred_phishing
)

final_roc_auc = roc_auc_score(
    y_test_phishing,
    y_test_proba_phishing
)

print("FINAL URL-ONLY PHISHING MODEL")
print("=" * 45)

print("Threshold:", URL_PHISHING_THRESHOLD)
print("Precision:", round(final_precision, 4))
print("Recall:", round(final_recall, 4))
print("F1-score:", round(final_f1, 4))
print("ROC-AUC:", round(final_roc_auc, 4))

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test_phishing,
        y_test_pred_phishing
    )
)

FINAL URL-ONLY PHISHING MODEL
=============================================
Threshold: 0.4
Precision: 0.998
Recall: 0.9948
F1-score: 0.9964
ROC-AUC: 0.9984

Confusion Matrix:
[[26930    40]
 [  104 20085]]

In [44]:
import re
from urllib.parse import urlparse
import pandas as pd


def extract_url_features(url):
    """
    Extract lexical features directly from a URL.
    These features do not require visiting the website.
    """

    url = str(url).strip()

    # Make URL parseable even when scheme is missing
    parse_url = url

    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", parse_url):
        parse_url = "//" + parse_url

    parsed = urlparse(parse_url)

    hostname = parsed.hostname or ""
    path = parsed.path or ""
    query = parsed.query or ""

    # Basic character counts
    letters = sum(char.isalpha() for char in url)
    digits = sum(char.isdigit() for char in url)

    special_characters = sum(
        not char.isalnum()
        for char in url
    )

    # IP address detection
    is_ip = int(
        bool(
            re.fullmatch(
                r"\d{1,3}(\.\d{1,3}){3}",
                hostname
            )
        )
    )

    # Domain characteristics
    domain_parts = hostname.split(".") if hostname else []

    if len(domain_parts) >= 2:
        subdomain_count = max(0, len(domain_parts) - 2)
        tld_length = len(domain_parts[-1])
    else:
        subdomain_count = 0
        tld_length = 0

    # Obfuscation indicators
    percent_encoded_count = len(
        re.findall(r"%[0-9A-Fa-f]{2}", url)
    )

    has_obfuscation = int(
        percent_encoded_count > 0
        or "@" in url
        or "\\" in url
    )

    # Ratios
    url_length = len(url)

    letter_ratio = (
        letters / url_length
        if url_length > 0 else 0
    )

    digit_ratio = (
        digits / url_length
        if url_length > 0 else 0
    )

    special_ratio = (
        special_characters / url_length
        if url_length > 0 else 0
    )

    return {
        "url_length": url_length,
        "domain_length": len(hostname),
        "is_ip": is_ip,
        "tld_length": tld_length,
        "subdomain_count": subdomain_count,
        "is_https": int(parsed.scheme.lower() == "https"),
        "letter_count": letters,
        "letter_ratio": letter_ratio,
        "digit_count": digits,
        "digit_ratio": digit_ratio,
        "equals_count": url.count("="),
        "question_count": url.count("?"),
        "ampersand_count": url.count("&"),
        "at_count": url.count("@"),
        "hyphen_count": url.count("-"),
        "dot_count": url.count("."),
        "percent_encoded_count": percent_encoded_count,
        "special_char_ratio": special_ratio
    }

In [45]:
test_urls = [
    "https://www.google.com",
    "https://example.com/login",
    "http://192.168.1.25/login",
    "https://secure-login-account-verify.example.com/account?user=test"
]

for url in test_urls:
    print("\nURL:")
    print(url)

    features = extract_url_features(url)

    for feature, value in features.items():
        print(f"{feature}: {value}")

URL:
https://www.google.com
url_length: 22
domain_length: 14
is_ip: 0
tld_length: 3
subdomain_count: 1
is_https: 1
letter_count: 17
letter_ratio: 0.7727272727272727
digit_count: 0
digit_ratio: 0.0
equals_count: 0
question_count: 0
ampersand_count: 0
at_count: 0
hyphen_count: 0
dot_count: 2
percent_encoded_count: 0
special_char_ratio: 0.22727272727272727

URL:
https://example.com/login
url_length: 25
domain_length: 11
is_ip: 0
tld_length: 3
subdomain_count: 0
is_https: 1
letter_count: 20
letter_ratio: 0.8
digit_count: 0
digit_ratio: 0.0
equals_count: 0
question_count: 0
ampersand_count: 0
at_count: 0
hyphen_count: 0
dot_count: 1
percent_encoded_count: 0
special_char_ratio: 0.2

URL:
http://192.168.1.25/login
url_length: 25
domain_length: 12
is_ip: 1
tld_length: 2
subdomain_count: 2
is_https: 0
letter_count: 9
letter_ratio: 0.36
digit_count: 9
digit_ratio: 0.36
equals_count: 0
question_count: 0
ampersand_count: 0
at_count: 0
hyphen_count: 0
dot_count: 3
percent_encoded_count: 0
special_char_ratio: 0.28

URL:
https://secure-login-account-verify.example.com/account?user=test
url_length: 65
domain_length: 39
is_ip: 0
tld_length: 3
subdomain_count: 1
is_https: 1
letter_count: 54
letter_ratio: 0.8307692307692308
digit_count: 0
digit_ratio: 0.0
equals_count: 1
question_count: 1
ampersand_count: 0
at_count: 0
hyphen_count: 3
dot_count: 2
percent_encoded_count: 0
special_char_ratio: 0.16923076923076924

In [46]:
# Generate the exact features our application will use

url_feature_data = X["URL"].apply(extract_url_features)

X_lexical = pd.DataFrame(
    url_feature_data.tolist(),
    index=X.index
)

print("Generated feature dataset successfully!")
print("Shape:", X_lexical.shape)

print("\nFeatures:")
print(X_lexical.columns.tolist())

print("\nMissing values:")
print(X_lexical.isnull().sum().sum())

Generated feature dataset successfully!
Shape: (235795, 18)

Features:
['url_length', 'domain_length', 'is_ip', 'tld_length', 'subdomain_count', 'is_https', 'letter_count', 'letter_ratio', 'digit_count', 'digit_ratio', 'equals_count', 'question_count', 'ampersand_count', 'at_count', 'hyphen_count', 'dot_count', 'percent_encoded_count', 'special_char_ratio']

Missing values:
0

In [47]:

X_lex_train, X_lex_test, y_lex_train, y_lex_test = train_test_split(
    X_lexical,
    y_phishing,
    test_size=0.20,
    random_state=42,
    stratify=y_phishing
)

print("Training samples:", X_lex_train.shape[0])
print("Testing samples:", X_lex_test.shape[0])

print("\nTraining class distribution:")
print(y_lex_train.value_counts())

print("\nTesting class distribution:")
print(y_lex_test.value_counts())

Training samples: 188636
Testing samples: 47159

Training class distribution:
label
1    107880
0     80756
Name: count, dtype: int64

Testing class distribution:
label
1    26970
0    20189
Name: count, dtype: int64

In [48]:
# Create a validation set from the training data

X_lex_train_final, X_lex_val, y_lex_train_final, y_lex_val = train_test_split(
    X_lex_train,
    y_lex_train,
    test_size=0.20,
    random_state=42,
    stratify=y_lex_train
)

print("Final training samples:", X_lex_train_final.shape[0])
print("Validation samples:", X_lex_val.shape[0])

print("\nValidation class distribution:")
print(y_lex_val.value_counts())

Final training samples: 150908
Validation samples: 37728

Validation class distribution:
label
1    21576
0    16152
Name: count, dtype: int64

In [49]:
from sklearn.ensemble import RandomForestClassifier

# Train the model using our own URL-derived features
custom_url_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

custom_url_model.fit(
    X_lex_train_final,
    y_lex_train_final
)

print("Custom URL phishing model trained successfully!")

Custom URL phishing model trained successfully!

In [50]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

# Get phishing probabilities
# UCI label 0 = Phishing
y_lex_val_proba_phishing = (
    custom_url_model.predict_proba(X_lex_val)[:, 0]
)

# Convert labels:
# 1 = Phishing
# 0 = Legitimate
y_lex_val_phishing = (y_lex_val == 0).astype(int)

# Use 0.50 temporarily for validation
y_lex_val_pred = (
    y_lex_val_proba_phishing >= 0.50
).astype(int)

precision = precision_score(
    y_lex_val_phishing,
    y_lex_val_pred
)

recall = recall_score(
    y_lex_val_phishing,
    y_lex_val_pred
)

f1 = f1_score(
    y_lex_val_phishing,
    y_lex_val_pred
)

roc_auc = roc_auc_score(
    y_lex_val_phishing,
    y_lex_val_proba_phishing
)

print("CUSTOM URL MODEL — VALIDATION")
print("=" * 45)

print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1-score:", round(f1, 4))
print("ROC-AUC:", round(roc_auc, 4))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_lex_val_phishing,
    y_lex_val_pred
))

CUSTOM URL MODEL — VALIDATION
=============================================
Precision: 0.9975
Recall: 0.9904
F1-score: 0.9939
ROC-AUC: 0.9974

Confusion Matrix:
[[21536    40]
 [  155 15997]]

In [51]:
# Tune the phishing threshold using the validation set

thresholds = [
    0.30, 0.35, 0.40, 0.45,
    0.50, 0.55, 0.60, 0.65, 0.70
]

print("Threshold | Precision | Recall | F1")
print("-" * 42)

for threshold in thresholds:

    y_val_pred = (
        y_lex_val_proba_phishing >= threshold
    ).astype(int)

    precision = precision_score(
        y_lex_val_phishing,
        y_val_pred
    )

    recall = recall_score(
        y_lex_val_phishing,
        y_val_pred
    )

    f1 = f1_score(
        y_lex_val_phishing,
        y_val_pred
    )

    print(
        f"{threshold:9.2f} | "
        f"{precision:9.3f} | "
        f"{recall:6.3f} | "
        f"{f1:5.3f}"
    )

Threshold | Precision | Recall | F1
------------------------------------------
     0.30 |     0.995 |  0.992 | 0.993
     0.35 |     0.996 |  0.991 | 0.993
     0.40 |     0.997 |  0.991 | 0.994
     0.45 |     0.997 |  0.991 | 0.994
     0.50 |     0.998 |  0.990 | 0.994
     0.55 |     0.998 |  0.990 | 0.994
     0.60 |     0.998 |  0.990 | 0.994
     0.65 |     0.998 |  0.990 | 0.994
     0.70 |     0.999 |  0.990 | 0.994

In [52]:
# Lock the threshold selected using validation data

CUSTOM_URL_THRESHOLD = 0.40

print("Locked custom URL phishing threshold:", CUSTOM_URL_THRESHOLD)

Locked custom URL phishing threshold: 0.4

In [53]:
# Train the final deployable URL phishing model
# using the complete training set

final_custom_url_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

final_custom_url_model.fit(
    X_lex_train,
    y_lex_train
)

print("Final custom URL phishing model trained successfully!")

Final custom URL phishing model trained successfully!

In [54]:
# Final evaluation of the custom URL phishing model

# Get phishing probabilities
# UCI label 0 = Phishing
y_final_proba_phishing = (
    final_custom_url_model.predict_proba(X_lex_test)[:, 0]
)

# Convert labels:
# 1 = Phishing
# 0 = Legitimate
y_final_phishing = (y_lex_test == 0).astype(int)

# Apply the locked threshold
y_final_pred = (
    y_final_proba_phishing >= CUSTOM_URL_THRESHOLD
).astype(int)

# Calculate final metrics
final_precision = precision_score(
    y_final_phishing,
    y_final_pred
)

final_recall = recall_score(
    y_final_phishing,
    y_final_pred
)

final_f1 = f1_score(
    y_final_phishing,
    y_final_pred
)

final_roc_auc = roc_auc_score(
    y_final_phishing,
    y_final_proba_phishing
)

print("FINAL CUSTOM URL PHISHING MODEL")
print("=" * 50)

print("Threshold:", CUSTOM_URL_THRESHOLD)
print("Precision:", round(final_precision, 4))
print("Recall:", round(final_recall, 4))
print("F1-score:", round(final_f1, 4))
print("ROC-AUC:", round(final_roc_auc, 4))

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_final_phishing,
        y_final_pred
    )
)

FINAL CUSTOM URL PHISHING MODEL
==================================================
Threshold: 0.4
Precision: 0.9962
Recall: 0.991
F1-score: 0.9936
ROC-AUC: 0.9973

Confusion Matrix:
[[26894    76]
 [  182 20007]]

In [55]:
import joblib
from pathlib import Path

# Create models directory if it doesn't exist
models_dir = Path("../models")
models_dir.mkdir(exist_ok=True)

# Save the final URL phishing model
joblib.dump(
    final_custom_url_model,
    models_dir / "url_phishing_model.pkl"
)

# Save the exact feature order
joblib.dump(
    list(X_lexical.columns),
    models_dir / "url_feature_columns.pkl"
)

# Save the locked threshold
joblib.dump(
    CUSTOM_URL_THRESHOLD,
    models_dir / "url_threshold.pkl"
)

print("URL phishing model artifacts saved successfully!")
print("\nSaved files:")

for file in [
    "url_phishing_model.pkl",
    "url_feature_columns.pkl",
    "url_threshold.pkl"
]:
    print("•", models_dir / file)

URL phishing model artifacts saved successfully!

Saved files:
• ..\models\url_phishing_model.pkl
• ..\models\url_feature_columns.pkl
• ..\models\url_threshold.pkl